version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage: 
    name: compile
    displayName: 后端编译
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: 21
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./target
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传后端制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: ai-edu-backend
        dependsOn: build_maven
  - stage: 
    name: frontend-build
    displayName: 前端编译
    steps:
      - step: build@nodejs
        name: build_frontend
        displayName: Node.js 构建
        nodeVersion: 20.10.0
        commands:
          - cd ai_edu_platform_frontend
          - npm install --legacy-peer-deps
          - npm run build
        artifacts:
          - name: FRONTEND_ARTIFACT
            path:
              - ./ai_edu_platform_frontend/dist
      - step: publish@general_artifacts
        name: publish_frontend_artifacts
        displayName: 上传前端制品
        dependArtifact: FRONTEND_ARTIFACT
        artifactName: ai-edu-frontend
        dependsOn: build_frontend
  - stage: 
    name: release
    displayName: 发布
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: '发布后端制品'
        # 上游上传制品任务的产出
        dependArtifact: ai-edu-backend
        # 发布制品版本号
        version: '1.0.0.0'
        # 是否开启版本号自增，默认开启
        autoIncrement: true
      - step: publish@release_artifacts
        name: publish_frontend_release
        displayName: '发布前端制品'
        dependArtifact: ai-edu-frontend
        version: '1.0.0.0'
        autoIncrement: true
triggers:
  push:
    branches:
      exclude:
        - main
      include:
        - .*
